#!/usr/bin/env python3
"""Run from any directory. Checked-in HTML lets GitHub Pages serve previews without JS."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FAMILY_COUNT = 100  # Keep in sync with WordNicePuzzleCatalog in the app.

for number in range(1, FAMILY_COUNT + 1):
    url = f"https://wordnice.app/family/{number}"
    title = f"Family {number} is all smiles. Your turn?"
    description = f"I made Family {number} happy in Word Nice. Come make a few words and a few smiles."
    image = f"https://wordnice.app/images/families/{number}.png"
    page = f'''<!DOCTYPE html>
<!-- Generated by tools/build-family-pages.py; edit the generator, then rerun it. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light">
<meta name="theme-color" content="#FFF9F1">
<title>{title} · Word Nice</title>
<meta name="description" content="{description}">
<link rel="canonical" href="{url}">
<link rel="icon" href="/images/favicon.png" type="image/png">
<link rel="apple-touch-icon" href="/images/apple-touch-icon.png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Word Nice">
<meta property="og:url" content="{url}">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<meta property="og:image" content="{image}">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Word Nice. Family {number}. All smiles. Your turn? An otter cuddles a letter above four smiling tiles.">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{description}">
<meta name="twitter:image" content="{image}">
<meta name="twitter:image:alt" content="Word Nice invites you to make Family {number} smile, with its otter and happy letter tiles.">
<link rel="stylesheet" href="/styles.css">
</head>
<body>
<div class="page family-page">
  <header><a class="family-brand" href="/">Word <span>Nice</span></a></header>
  <main class="family-invitation">
    <img class="family-preview" src="/images/families/{number}.png" width="1200" height="630"
         alt="Word Nice. Family {number}. All smiles. Your turn?">
    <div class="family-copy">
      <p class="family-eyebrow">A little kindness, passed along</p>
      <h1>Make Family {number} smile.</h1>
      <p>Someone made this family happy and thought of you. Find a few words, include every letter, and see what they have to say.</p>
      <p class="family-gentle">No timer. No score. Just a little good.</p>
      <a class="family-button" href="/">Meet Word Nice <span aria-hidden="true">↗</span></a>
      <p class="family-availability">Coming soon to iPhone &amp; iPad.</p>
      <p class="family-help">Already have Word Nice? Tap the original link in your message to meet this family in the app.</p>
    </div>
  </main>
  <footer class="family-footer">A little good in every word.</footer>
</div>
</body>
</html>
'''
    target = ROOT / "family" / str(number) / "index.html"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(page)
print(f"Built {FAMILY_COUNT} static family pages.")
